# Publish Settings
backend:
  name: git-gateway
  branch: 'video-banners' # Change to your local branch for testing. 
publish_mode: editorial_workflow

# Media
media_folder: "source/static/uploads"
public_folder: "static/uploads"

# Content Types
collections:

  # Home page
  - name: "home"
    label: "Home"
    editor:
      preview: false
    files:
      - label: "Home"
        name: "home"
        file: "source/_data/home.yml"
        fields:   
          - name: "cover_image"
            label: "Cover image"
            widget: object
            required: false
            hint: "The large banner at the top of the homepage."
            fields: 
              - name: "source"
                label: "Image"
                widget: "image"
                required: false,
                allow_multiple: false
              - name: "alt"
                label: "Alternate label"
                widget: "string"
                required: false
                hint: "An alternate label (alt attribute) that will display if the image doesn't load correctly, or if the user is using a screen reader."

  # Customer photos (instagram)
  - name: "customer_photos"
    label: "Customer photos"
    editor:
      preview: false
    files:
      - label: "Photos"
        name: "photos"
        file: "source/_data/customer_photos.yml"
        fields:
          - name: "photos"
            label: "Photos"
            widget: list
            required: false
            hint: "The photos displayed on the homepage in the customer photos (#ShareAndSmile) section. Note the homepage is limited to 16 photos, to keep it from getting too huge."
            fields:
              - {label: "Source", name: "source", widget: "image"}
              - {label: "Link", name: "url", widget: "string", hint: "The link/url of the original image on Instagram."}
              - {label: "Description (alt tag)", name: "alt", widget: "string", required: false, hint: "A short description/caption for the image; will be used as the alt tag."}


  # Catalog Topics
  # Description: 
  #   Catalog topcis are topics that are used to group catalogs.
  #   These are used to fill the drop-down on the product menu.
  - name: "catalog_topics"
    label: "Catalog Topics"
    folder: "source/_posts/inventory/catalog_topics"
    editor:
      preview: false
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Published Status", name: "published", widget: "hidden", default: true}     
      - {label: "ID", name: "unique_id", widget: "string", hint: 'This ID is used to associate this with other items, it must be unique and dont change it once its set.'}
      - {label: "Topic Name", name: "title", widget: "string"}
      - {label: "Cover Image", name: "image", widget: "image", allow_multiple: false, required: false, hint: "This is the image displayed on the top of the topic page"}
      - {label: "Thumbnail Image", name: "thumbnail", widget: "image", allow_multiple: false, required: false, hint: "This is a smaller image displayed on cards in lists, such as the 'More topics' section at the bottom of the topic page."}

  # Catalogs
  # Description: 
  #   A catalog is a grouping of products, with an associated PDF
  - name: "catalogs"
    label: "Catalogs"
    folder: "source/_posts/inventory/catalogs"
    editor:
      preview: false
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Published Status", name: "published", widget: "hidden", default: true}     
      - {label: "ID", name: "unique_id", widget: "string", hint: 'This ID is used to associate this with other items, it must be unique and dont change it once its set.'}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured", name: "featured", widget: "boolean", required: false, hint: "If a catalog is featured, it will be listed on the home page"}
      - {label: "Catalog PDF", name: "pdf", widget: "file", allow_multiple: false, required: false, hint: "This is the catalog file that can be downloaded"}
      - {label: "Cover Image", name: "cover", widget: "image", allow_multiple: false, required: false, hint: "This is the image displayed on the top of the catalog page, and the home if the catalog is featured."}
      - {label: "Thumbnail Image", name: "thumbnail", widget: "image", allow_multiple: false, required: false, hint: "This is a smaller image displayed on cards in lists, such as on the 'all products' page."}
      - label: "Catalog Topic"
        name: "topic"
        widget: "relation"
        collection: "catalog_topics"
        searchFields: ["title"]
        displayFields: "title"
        valueField: "unique_id"
        multiple: true
        required: false
        hint: "This allows you to relate the catalog to a topic, a topic is what is used in the dropdown area on the home page."

  # Product Collections
  # Description: 
  #   Product collections are groupings of products by a an arbitrary concept (ie mermaids)
  #   These are used to showcase products in a variety of contexts and function akin to tags.
  - name: "product_collections"
    label: "Product Collections"
    folder: "source/_posts/inventory/product_collections"
    editor:
      preview: false
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Published Status", name: "published", widget: "hidden", default: true}     
      - {label: "ID", name: "unique_id", widget: "string", hint: 'This ID is used to associate this with other items, it must be unique and dont change it once its set.'}
      - {label: "Collection Name", name: "title", widget: "string"}
      - {label: "Cover Image", name: "cover", widget: "image", allow_multiple: false, hint: "This is the image displayed on the top of the collection page, and the home if the collection is featured."}
      - {label: "Cover Video", name: "video", widget: "string", required: false, hint: "You can, optionally, display a video instead of a cover image for the topic. Add the url of the video here."}
      - {label: "Thumbnail Image", name: "thumbnail", widget: "image", allow_multiple: false, required: false, hint: "This is a smaller image displayed on cards in lists, such as on the 'all products' page."}
      - {label: "Featured", name: "featured", widget: "boolean", required: false, hint: "If a product collection is featured, it will be listed on the home page"}

  # Products
  # Description: 
  #   A Product is a single product unit, it is in catalogs and collections.
  - name: "product"
    label: "Products"
    folder: "source/_posts/inventory/products"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}-{{size}}in"
    fields: # The fields for each document, usually in front matter
      - {label: "Published Status", name: "published", widget: "hidden", default: true}     
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured", name: "featured", widget: "boolean", required: false, hint: "If a product is featured, it will be listed as one of the featured products on the home page in a catalog or collection"}
      - {label: "Size (inches)", name: "size", widget: "string", required: false, hint: "The size in inches. Do not add any units or quote marks here - these will be added in the templates as needed."}
      - {label: "Item Number", name: "item_number", widget: "string", required: false}
      - {label: "Color", name: "color", widget: "string", required: false}    
      - {label: "Product Image", name: "image", widget: "image", allow_multiple: false}
      - {label: "Thumbnail Image", name: "thumbnail", widget: "image", allow_multiple: false, required: false, hint: "This is a smaller image displayed on cards in lists, such as on a catalog or collection page."}
      - label: "Catalog"
        name: "catalog"
        widget: "relation"
        collection: "catalogs"
        searchFields: ["title"]
        displayFields: "title"
        valueField: "unique_id"
        multiple: true
        required: false
        hint: "This associates the product with one or many catalogs"
      - label: "Product Collection"
        name: "product_collections"
        widget: "relation"
        collection: "product_collections"
        searchFields: ["title"]
        displayFields: "title"
        valueField: "unique_id"
        multiple: true
        required: false
        hint: "This associates the product with one or many collections"
      - {label: "Product Description", name: "body", widget: "markdown", required: false}

  # Custom Products
  # Description: 
  #   These are examples of custom products
  - name: "custom_products"
    label: "Custom Products"
    editor:
      preview: false
    files: 
      - label: "Custom Products"
        name: "custom_products"
        file: "source/_data/custom_products.yml"
        fields:
          - name: "listings"
            label: "Listings"
            label_singular: "Listing"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string", hint: "The name of the custom product collection, e.g. 'hoodies'."}
              - {label: "Description", name: "description", widget: "markdown", required: false, hint: "A short (optional) product descrption."}
              - label: "Images"
                name: "images"
                widget: "list"
                hint: "Product images. Add as many as you like."
                fields:
                  - {label: "Source", name: "source", widget: "image"}
                  - {label: "Alternate label", name: "alt", widget: "string", hint: "An alternate description (alt attribute) for the image, in case it does not load or the user is using a screen reader."}

  # News pages
  - name: "news" # Used in routes, e.g., /admin/collections/blog
    label: "News" # Used in the UI
    folder: "source/_posts/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Published Status", name: "published", widget: "hidden", default: true}
      - {label: "Body", name: "body", widget: "markdown"}

  # Staff
  - name: "staff"
    label: "Staff"
    folder: "source/_posts/staff"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Job Title", name: "job_title", widget: "string"}
      - {label: "Email", name: "email", widget: "string"}
      - {label: "Published Status", name: "published", widget: "hidden", default: true}      
  
  # Testimonials
  - name: "testimonials"
    label: "Testimonials"
    editor:
      preview: false
    files: 
      - label: "Testimonials"
        name: "testimonials"
        file: "source/_data/testimonials.yml"
        fields:
          - name: "quotes"
            label: "Quotes"
            widget: "list"
            fields:
              - {label: "Quote", name: "quote", widget: "markdown"}
              - {label: "Attribution", name: "attribution", widget: "string", required: false, hint: "The name of the person who said this quote."}

  # FAQ
  - name: "faq"
    label: "FAQ"
    editor:
      preview: false
    files:
      - label: "FAQ"
        name: "faq"
        file: "source/_data/faq.yml"
        fields:          
          - name: "faq"
            label: "FAQ"
            widget: "list"
            fields: 
              - {label: "Question", name: "question", widget: "string"}
              - {label: "Answer", name: "answer", widget: "markdown"}

  # Intros
  # Description: 
  #   These are pieces of content that are showcased across the site, mostly as "intros".
  - name: "intro_text"
    label: "Intros"
    folder: "source/_posts/intros"
    description: "These are pieces of content that are showcased across the site, mostly as introductions."
    create: false
    delete: false
    identifier_field: label
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{label}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Published Status", name: "published", widget: "hidden", default: true} 
      - {label: "Label", name: "label", widget: "hidden"}
      - {label: "Title", name: "display_title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Categories"
        name: "categories"
        widget: "hidden"

  # Main Navigation
  - name: "nav"
    label: "Main Navigation"
    editor:
      preview: false
    files:
      - label: "Main Navigation"
        name: "main_nav"
        file: "source/_data/navigation.yml"
        fields:          
          - name: "navigation_items"
            label: "Navigation Items"
            label_singular: "Navigation Item"
            widget: "list"
            fields: 
              - {label: "Text Label", name: "label", widget: "string", hint: "This is what will appear in the main menu on-screen."}
              - {label: "URL", name: "url", widget: "string", hint: "This is the address where the link will point. Use a 'relative path', without the domain name (e.g. '/collections/sloths/')."}        
              - label: "Submenu"
                label_singular: "Submenu item"
                name: "submenu"
                widget: "list"
                default: false
                required: false
                hint: "If you add a submenu, it will appear as a dropdown on larger screens."
                fields:
                  - {label: "Text Label", name: "label", widget: "string", hint: "This is what will appear in the submenu or dropdown on-screen."}
                  - {label: "URL", name: "url", widget: "string", hint: "This is the address where the link will point. Use a 'relative path', without the domain name (e.g. '/collections/sloths/')."}

  # Site Settings
  - name: "config"
    label: "Site Settings"
    editor:
      preview: false
    files:
      - label: "Contact Information"
        name: "contact"
        file: "source/_data/contact.yml"
        fields:          
          - name: "address"
            label: "Address"
            widget: "object"
            fields: 
              - {label: "Street", name: "street", widget: "string"}
              - {label: "City", name: "city", widget: "string"}
              - {label: "State", name: "state", widget: "string"}
              - {label: "Zip", name: "zip", widget: "string"}
          - name: "phone"
            label: "Phone"
            widget: "string"
          - name: "email"
            label: "Email"
            widget: "string"
          - name: "contact_subjects"
            label: "Contact form subject dropdown"
            hint: "The contact form has a dropdown button with subjects users can choose for the email they send. You can edit those options here."
            widget: "object"
            fields: 
              - {label: "Question", name: "question", widget: "string"}
              - label: "Answers"
                name: "answers"
                widget: "list"
                fields:
                  - {label: "Option", name: "option", widget: "string", hint: "Describe the email subject in first-person, e.g. 'I'd like to place an order.'"}
                  - {label: "Value", name: "value", widget: "string", hint: "A keyword the form uses to send information. Use a 1-2 word summary of the Option field with no spaces, e.g. 'order_question'"}
          - name: "order_form"
            label: "Order Form"
            widget: "file"
            allow_multiple: false
            hint: "The order form PDF that users can download from the Contact page."
          - name: "social"
            label: "Social Media Platform"
            widget: "list"
            fields: 
              - {label: "Platform name", name: "platform", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
              - {label: "Icon", name: "icon", widget: "string", required: false}
          
            