# Publish Settings
backend:
  name: git-gateway
  branch: 'dev' # Change to your local branch for testing. 
publish_mode: editorial_workflow

# Media
media_folder: "source/static/uploads"
public_folder: "static/uploads"

# Content Types
collections:

  # News pages
  - name: "news" # Used in routes, e.g., /admin/collections/blog
    label: "News" # Used in the UI
    folder: "source/_posts/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date", format: "MMM Do YY", hint: "This is the date displayed for this news post"}
      - {label: "Published Status", name: "published", widget: "hidden", default: true}
      - {label: "Body", name: "body", widget: "markdown"}

  # Staff
  - name: "staff"
    label: "Staff"
    folder: "source/_posts/staff"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Job Title", name: "job_title", widget: "string"}
      - {label: "Email", name: "email", widget: "string"}
      - {label: "Portrait", name: "portrait", allow_multiple: false, widget: "image", required: false}
      - {label: "Published Status", name: "published", widget: "hidden", default: true}      
  
  # Testimonials
  - name: "testimonials"
    label: "Testimonials"
    folder: "source/_posts/testimonials"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
      - {label: "Published Status", name: "published", widget: "hidden", default: true}     
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  # Catalog Topics
  # Description: 
  #   Catalog topcis are topics that are used to group catalogs.
  #   These are used to fill the drop-down on the product menu.
  - name: "catalog_topics"
    label: "Catalog Topics"
    folder: "source/_posts/inventory/catalog_topics"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Published Status", name: "published", widget: "hidden", default: true}     
      - {label: "Category", name: "category", widget: "hidden", default: "catalog_topic"}
      - {label: "ID", name: "unique_id", widget: "string", hint: 'This ID is used to associate this with other items, it must be unique and dont change it once its set.'}
      - {label: "Topic Name", name: "title", widget: "string"}
      - {label: "Catalog Topic Cover", name: "image", widget: "image", allow_multiple: false, required: false, hint: "This is the image displayed on the top of the topic page"}

  # Catalogs
  # Description: 
  #   A catalog is a grouping of products, with an associated PDF
  - name: "catalogs"
    label: "Catalogs"
    folder: "source/_posts/inventory/catalogs"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "catalog"}
      - {label: "Published Status", name: "published", widget: "hidden", default: true}     
      - {label: "Show Products", name: "show_products", widget: "hidden", default: true}
      - {label: "Category", name: "category", widget: "hidden", default: "catalogs"}
      - {label: "ID", name: "unique_id", widget: "string", hint: 'This ID is used to associate this with other items, it must be unique and dont change it once its set.'}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Catalog PDF", name: "pdf", widget: "file", allow_multiple: false, required: false, hint: "This is the catalog file that can be downloaded"}
      - {label: "Catalog Cover", name: "cover", widget: "image", allow_multiple: false, required: false, hint: "This is the image displayed on the top of the catalog page"}
      - label: "Catalog Topic"
        name: "topic"
        widget: "relation"
        collection: "catalog_topics"
        searchFields: ["title"]
        displayFields: "title"
        valueField: "unique_id"
        multiple: true
        required: false
        hint: "This allows you to relate the catalog to a topic, a topic is what is used in the dropdown area on the home page."
      - {label: "Featured", name: "featured", widget: "boolean", required: false, hint: "If a catalog is featured, it will be listed on the home page"}

  # Product Collections
  # Description: 
  #   Product collections are groupings of products by a an arbitrary concept (ie mermaids)
  #   These are used to showcase products in a variety of contexts and function akin to tags.
  - name: "product_collections"
    label: "Product Collections"
    folder: "source/_posts/inventory/product_collections"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Published Status", name: "published", widget: "hidden", default: true}     
      - {label: "Category", name: "category", widget: "hidden", default: "product_collection"}
      - {label: "ID", name: "unique_id", widget: "string", hint: 'This ID is used to associate this with other items, it must be unique and dont change it once its set.'}
      - {label: "Collection Name", name: "title", widget: "string"}
      - {label: "Product Collection Cover", name: "image", widget: "image", allow_multiple: false, hint: "This is the image displayed on the top of the collection page"}
      - {label: "Featured", name: "featured", widget: "boolean", required: false, hint: "If a product collection is featured, it will be listed on the home page"}

  # Products
  # Description: 
  #   A Product is a single product unit, it is in catalogs and collections.
  - name: "product"
    label: "Products"
    folder: "source/_posts/inventory/products"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "product"}
      - {label: "Published Status", name: "published", widget: "hidden", default: true}     
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured", name: "featured", widget: "boolean", required: false, hint: "If a product is featured, it will be listed as one of the featured products on the home page in a catalog or collection"}
      - {label: "SKU", name: "sku", widget: "string", required: false}
      - {label: "Color", name: "color", widget: "string", required: false}    
      - {label: "Product Image", name: "image", widget: "image", allow_multiple: false}
      - label: "Catalog"
        name: "catalog"
        widget: "relation"
        collection: "catalogs"
        searchFields: ["title"]
        displayFields: "title"
        valueField: "unique_id"
        multiple: true
        required: false
        hint: "This associates the product with one or many catalogs"
      - label: "Product Collection"
        name: "product_collections"
        widget: "relation"
        collection: "product_collections"
        searchFields: ["title"]
        displayFields: "title"
        valueField: "unique_id"
        multiple: true
        required: false
        hint: "This associates the product with one or many collections"
      - {label: "Product Description", name: "body", widget: "markdown", required: false}

  # Intros
  # Description: 
  #   These are pieces of content that are showcased across the site, mostly as "intros".
  - name: "intro_text"
    label: "Intros"
    folder: "source/_posts/intros"
    description: "These are pieces of content that are showcased across the site, mostly as introductions."
    create: false
    delete: false
    identifier_field: label
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{label}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
      - {label: "Published Status", name: "published", widget: "hidden", default: true}     
      - {label: "Title", name: "display_title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  # Custom Products
  # Description: 
  #   These are examples of custom products
  - name: "custom_products"
    label: "Custom Products"
    folder: "source/_posts/inventory/custom_products"
    create: false
    delete: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
      - {label: "Category", name: "category", widget: "hidden", default: "custom"}
      - {label: "Published Status", name: "published", widget: "hidden", default: true}     
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  # Main Navigation & Dropdown
  - name: "nav"
    label: "Main Navigation"
    editor:
      preview: false
    files:
      - label: "Main Navigation"
        name: "main_nav"
        file: "source/_data/navigation.yml"
        fields:          
          - name: "navigation_items"
            label: "Navigation Items"
            label_singular: "Navigation Item"
            widget: "list"
            fields: 
              - {label: "Text Label", name: "label", widget: "string", hint: "This is what will appear in the main menu on-screen."}
              - {label: "URL", name: "url", widget: "string", hint: "This is the address where the link will point. Use a 'relative path', without the domain name (e.g. '/collections/sloths/')."}        
              - name: "submenu"
                label: "Submenu"
                label_singular: "Submenu item"
                widget: "list"
                default: false
                required: false
                fields:
                  - {label: "Text Label", name: "label", widget: "string", hint: "This is what will appear in the submenu or dropdown on-screen."}
                  - {label: "URL", name: "url", widget: "string", hint: "This is the address where the link will point. Use a 'relative path', without the domain name (e.g. '/collections/sloths/')."}
                                      
  # FAQ
  - name: "faq"
    label: "FAQ"
    editor:
      preview: false
    files:
      - label: "FAQ"
        name: "faq"
        file: "source/_data/faq.yml"
        fields:          
          - name: "FAQ"
            label: "FAQ"
            widget: "list"
            fields: 
              - {label: "Question", name: "question", widget: "string"}
              - {label: "Answer", name: "answer", widget: "markdown"}

  # Site Settings
  - name: "config"
    label: "Site Settings"
    editor:
      preview: false
    files:
      - label: "Contact Information"
        name: "contact"
        file: "source/_data/contact.yml"
        fields:          
          - name: "address"
            label: "Address"
            widget: "object"
            fields: 
              - {label: "Street", name: "street", widget: "string"}
              - {label: "City", name: "city", widget: "string"}
              - {label: "State", name: "state", widget: "string"}
              - {label: "Zip", name: "zip", widget: "string"}
          - name: "phone"
            label: "Phone"
            widget: "object"
            fields: 
              - {label: "Office", name: "office", widget: "string"}
              - {label: "Fax", name: "fax", widget: "string"}
          - name: "email"
            label: "Email"
            widget: "object"
            fields: 
              - {label: "Sales", name: "sales", widget: "string"}
          - name: "social"
            label: "Social Media Platform"
            widget: "list"
            fields: 
              - {label: "Platform name", name: "platform", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
              - {label: "Icon", name: "icon", widget: "string"}
          
            